backend:
  name: git-gateway
  branch: main

# publish_mode: editorial_workflow
media_folder: "assets/imgs/uploads"
public_folder: "/assets/imgs/uploads"

collections:
  - name: "departamentos" # Used in routes, e.g., /admin/collections/blog
    label: "Departamentos" # Used in the UI
    folder: "src/departamentos" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    editor:
      preview: false # Disable the editor preview and use instead 'preview links'
    fields: # The fields for each document, usually in front matter
      - { name: "title", label: "Departamento" }
      - { name: "descripcion", label: "Descripción", widget: "markdown" }
  - name: "municipalidades" # Used in routes, e.g., /admin/collections/blog
    label: "Municipalidades" # Used in the UI
    folder: "src/municipalidades" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    editor:
      preview: false # Disable the editor preview and use instead 'preview links'
    fields: # The fields for each document, usually in front matter
      - { name: "title", label: "Municipalidad" }
      - { name: "icono", label: "Icono de Categoría", widget: "image" }
      - { name: "descripcion", label: "Descripción", widget: "markdown" }
      - { name: "direccion", label: "Dirección" }
      - { name: "horario", label: "Horario de Atención" }
      - { name: "dias_abiertos", label: "Días Abiertos" }
      - { name: "pagina_web", label: "Página Web" }
      - { name: "corrreo_electronico", label: "Correo Electrónico" }
      - { name: "facebook", label: "Facebook" }
      - { name: "twitter", label: "Twitter" }
  - name: "categorias" # Used in routes, e.g., /admin/collections/blog
    label: "Categorias" # Used in the UI
    folder: "src/categorias" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    editor:
      preview: false # Disable the editor preview and use instead 'preview links'
    fields: # The fields for each document, usually in front matter
      - { name: "title", label: "Categoría" }
      - { name: "icono", label: "Icono de la Categoría", widget: "image" }
      - { name: "descripcion", label: "Descripción", widget: "markdown" }
  - name: "subcategorias" # Used in routes, e.g., /admin/collections/blog
    label: "Subcategorias" # Used in the UI
    folder: "src/subcategorias" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    editor:
      preview: false # Disable the editor preview and use instead 'preview links'
    fields: # The fields for each document, usually in front matter
      - { name: "title", label: "Subcategoría" }
      - { name: "icono", label: "Icono de Subcategoría", widget: "image" }
      - {
          label: "Categoría",
          name: "categoria",
          widget: "relation",
          collection: "categorias",
          search_fields: ["title"],
          value_field: "title",
          multiple: false,
        }
      - { name: "descripcion", label: "Descripción", widget: "markdown" }
